# Generated by Django 3.0.2 on 2020-01-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feira',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='feira',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
