# Generated by Django 3.0.2 on 2020-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0002_auto_20200129_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(max_length=100)),
            ],
        ),
    ]
