# Generated by Django 3.0.2 on 2020-01-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0003_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='local',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='feirasApp.Local'),
            preserve_default=False,
        ),
    ]
