# Generated by Django 3.0.2 on 2020-02-02 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0005_auto_20200202_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='semana',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
