# Generated by Django 3.0.2 on 2020-02-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0006_auto_20200202_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Todas'), (1, 'Primeira'), (2, 'Segunda'), (3, 'Terceira'), (4, 'Quarta'), (5, 'Quinta')], null=True),
        ),
    ]
