 # Generated by Django 3.0.2 on 2020-02-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feirasApp', '0007_auto_20200202_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='feira',
            name='fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='feira',
            name='inicio',
            field=models.TimeField(null=True),
        ),
    ]
